SistemaControleLuminosidade/Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SistemaControleLuminosidade.Repositore;

namespace SistemaControleLuminosidade.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;

        public LoginController(ILogger<LoginController> logger)
        {
            _logger = logger;
        }
        public ActionResult Login()
        {
            return View();
        }

        public string FazerLogin(string usuario, string senha)
        {
            try
            {
                UsuarioRepositore repositore = new UsuarioRepositore();
                var login = repositore.FazerLogin(usuario, senha);
                if (login != null && login.tipo_usuario == "admin")
                {
                    return "admin";
                }
                else if (login != null && login.tipo_usuario == "normal")
                {
                    return "normal";
                }
                else
                {
                    return "";
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                throw new Exception(ex.Message);
            }

        }
    }
}

SistemaControleLuminosidade/Controllers/OcorrenciaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SistemaControleLuminosidade.Models;
using SistemaControleLuminosidade.Repositore;

namespace SistemaControleLuminosidade.Controllers
{
    public class OcorrenciaController : Controller
    {
        public ActionResult PainelOcorrenciaAdmin()
        {
            OcorrenciaRepositore repositore = new OcorrenciaRepositore();
            return View(repositore.BuscarOcorrencias());
        }

        public ActionResult PainelOcorrenciaMorador()
        {
            OcorrenciaRepositore repositore = new OcorrenciaRepositore();
            return View(repositore.BuscarOcorrencias());
        }

        public ActionResult CadastroOcorrencia()
        {
            return View();
        }

        public ActionResult CadastroOcorrenciaMorador()
        {
            return View();
        }

        public string CadastrarOcorrencia(string descricao)
        {
            tb_ocorrencia ocorrencia = new tb_ocorrencia();
            ocorrencia.descricao = descricao;
            ocorrencia.status_ocorrencia = "Aberta";
            ocorrencia.data_inclusao = DateTime.Now;
            OcorrenciaRepositore repositore = new OcorrenciaRepositore();
            repositore.CadastrarOcorrencia(ocorrencia);
            return "Ocorrencia cadastrada com sucesso";
        }

        public IActionResult DetalhesOcorrencia(int id_ocorrencia) 
        {
            OcorrenciaRepositore Repositore = new OcorrenciaRepositore();
            var lampada = Repositore.BuscarOcorrenciaPorId(id_ocorrencia);
            return View(lampada);
        }

        public string FinalizarOcorrencia(int id_ocorrencia) 
        {
            OcorrenciaRepositore Repositore = new OcorrenciaRepositore();
            var ocorrencia = Repositore.BuscarOcorrenciaPorId(id_ocorrencia);
            Repositore.FinalizarOcorrencia(ocorrencia);
            return "A ocorrência foi finalizada";
        }
    }
}

SistemaControleLuminosidade/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema de Controle de Luminosidade</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaControleLuminosidade.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="PainelLampadas">Sistema de Controle de Luminosidade</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="PainelLampadas">Lampadas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="PainelSensores">Sensores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="PainelEstoque">Estoque</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ocorrencia" asp-action="PainelOcorrenciaAdmin">Ocorrências</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Sair</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Sistema de Controle de Luminosidade
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SistemaControleLuminosidade/Views/Shared/_LayoutMorador.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema de Controle de Luminosidade</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaControleLuminosidade.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Ocorrencia" asp-action="PainelOcorrenciaMorador">Sistema de Controle de Luminosidade</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Sair</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Sistema de Controle de Luminosidade
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>